#!/bin/bash

# Launch the program files using dotnet watch
dotnet run --project ApiGateway.Gateway/ApiGateway.Gateway.csproj &
dotnet run --project ApiGateway.MongoDB/ApiGateway.MongoDB.csproj &
dotnet run --project ApiGateway.SQLServer/ApiGateway.SQLServer.csproj &